---
git:
  submodules: false
bundler_args: --without development debug
services:
  - mysql2
before_install:
  - sudo apt-get update
  - sudo apt-get install mediainfo
  - sudo ln -s /usr/bin/lsof /usr/sbin/lsof
  - cp spec/config/*.yml config
  - bundle config without development:production
before_script:
  - mysql -e 'create database avalon_test;'
  - bundle exec rake delayed_job:start
  - bundle exec rake db:migrate
language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.2.5
  - 2.3.1
addons:
  code_climate:
    repo_token: 1fb78f221b36e5615428f2ada12950b39a3b702b23fdd41e1b980dc4b47d0233
