---
git:
  submodules: false
bundler_args: --with mysql aws --without development debug
services:
  - mysql2
before_install:
  - sudo apt-get update
  - sudo apt-get install mediainfo
  - sudo ln -s /usr/bin/lsof /usr/sbin/lsof
  - cp config/authentication.yml.example config/authentication.yml
  - cp config/controlled_vocabulary.yml.example config/controlled_vocabulary.yml
  - cp config/avalon.yml.example config/avalon.yml
  - bundle config without development:production
before_script:
  - rm config/database.yml
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database avalon_test;'
  - bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.3
  - 2.4
dist: precise
