units:
  - Test Content From Evaluators
  - Evaluator Collections
  - Avalon Media System
  - Samvera Community
  - Sample Content
identifier_types:
  local: Catalog Key
  oclc: OCLC
  lccn: LCCN
  issue number: Issue Number
  matrix number: Matrix Number
  music publisher: Music Publisher/Label
  videorecording identifier: Videorecording Identifier
  other: Other
note_types:
  general: General Note
  awards: Awards
  biographical/historical: Bibliographical/Historical Note
  creation/production credits: Creation/Production Credits
  language: Language Note
  local: Local Note
  performers: Performers
  statement of responsibility: Statement of Responsibility
  venue: Venue/Event Date
rights_statements:
  http://rightsstatements.org/vocab/InC/1.0/: In Copyright
  http://rightsstatements.org/vocab/InC-OW-EU/1.0/: In Copyright - EU Orphan Work
  http://rightsstatements.org/vocab/InC-EDU/1.0/: In Copyright - Educational Use Permitted
  http://rightsstatements.org/vocab/InC-NC/1.0/: In Copyright - Non-Commercial Use Permitted
  http://rightsstatements.org/vocab/InC-RUU/1.0/: In Copyright - Rights-Holders Unlocatable or Unidentifiable
  http://rightsstatements.org/vocab/NoC-CR/1.0/: No Copyright - Contractual Restrictions
  http://rightsstatements.org/vocab/NoC-NC/1.0/: No Copyright - Non-Commercial Use Only
  http://rightsstatements.org/vocab/NoC-OKLR/1.0/: No Copyright - Other Known Legal Restrictions
  http://rightsstatements.org/vocab/NoC-US/1.0/: No Copyright - United States
  http://rightsstatements.org/vocab/CNE/1.0/: Copyright Not Evaluated
  http://rightsstatements.org/vocab/UND/1.0/: Copyright Undetermined
  http://rightsstatements.org/vocab/NKC/1.0/: No Known Copyright
