collection_manager:
  - archivist1@example.com
  - archivist2
  - pdinh
  - mnotess
  - jwd
  - rogersna
  - cjcolvar
  - jlhardes
  - bhmarsha
  - chris.colvard@gmail.com
  - azielke@northwestern.edu
  - michael.klein@northwestern.edu
  - j-rudder@northwestern.edu
  - stefanelnabli@northwestern.edu
  - adam.t.hallett@gmail.com
  - claire-stewart@northwestern.edu
  - stubaker@northwestern.edu
  - k-miller3@northwestern.edu
  - brendan-quinn@northwestern.edu
registered:
  - pdinh
  - rogersna
  - cjcolvar
group_manager:
  - archivist1@example.com
  - pdinh
  - cjcolvar
  - rogersna
  - mnotess
  - jwd
  - jlhardes
  - chris.colvard@gmail.com
  - azielke@northwestern.edu
  - michael.klein@northwestern.edu
  - j-rudder@northwestern.edu
  - stefanelnabli@northwestern.edu
  - adam.t.hallett@gmail.com
  - brendan-quinn@northwestern.edu
