archivist:
  - archivist1
  - archivist2
  - archivist1@example.com
  - archivist2@example.com
  - leland_himself@example.com
collection_manager:
  - archivist1
  - archivist2
  - archivist1@example.com
  - archivist2@example.com
  - leland_himself@example.com
group_manager:
  - archivist1
  - archivist1@example.com
