development:
  administrator:
    - archivist1@example.com
  manager:
    - archivist1@example.com
  group_manager:
    - archivist1@example.com
  unit_administrator:
    - archivist1@example.com

test:
  administrator:
    - archivist1@example.com
    -
  manager:
    - archivist1@example.com
    -
  group_manager:
    - archivist1@example.com
    -
  unit_administrator:
    - archivist1@example.com

production:
  # Add roles for users here.
  administrator:
    - <%= Settings.initial_user %>
  manager:
    - <%= Settings.initial_user %>
  group_manager:
    - <%= Settings.initial_user %>
  unit_administrator:
    - <%= Settings.initial_user %>
