development:
  administrator:
    - archivist1@example.com
  manager:
    - archivist1@example.com
  group_manager:
    - archivist1@example.com

test:
  administrator:
    - 
  manager:
    -
  group_manager:
    -

production:
  # Add roles for users here.
