---
generic:
  http:
    video: <%=http_base%>/<%=path%>/<%=filename%>.<%=extension%>.m3u8
    audio: <%=http_base%>/<%=path%>/<%=filename%>.<%=extension%>.m3u8
adobe:
  http:
    video: <%=http_base%>/<%=path%>/<%=filename%>.<%=extension%>.m3u8
    audio: <%=http_base%>/audio-only/<%=path%>/<%=filename%>.<%=extension%>.m3u8
wowza:
  http:
    video: <%=http_base%>/<%=extension%>:minio/<%=path%>/<%=filename%>.<%=extension%>/playlist.m3u8
    audio: <%=http_base%>/<%=extension%>:minio/<%=path%>/<%=filename%>.<%=extension%>/playlist.m3u8
nginx:
  http:
    video: <%=http_base%>/<%=path%>/<%=filename%>.<%=extension%>/index.m3u8
    audio: <%=http_base%>/<%=path%>/<%=filename%>.<%=extension%>/index.m3u8
    
