version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "develop"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "develop"
