domain:
  host: test.host
dropbox:
  upload_uri: smb://test.host/dropbox
auth:
  configuration:
    - :name: Avalon Lti OAuth
      :provider: :lti
      :hidden: true
      :params:
        :oauth_credentials:
          key: 'secret'
encoding:
  engine_adapter: test
email: 
  mailer:
